# Generated by Django 4.1.2 on 2022-10-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transaction_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Tehran', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='989000000', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(default='Tehran', max_length=255),
        ),
    ]
