# Generated by Django 4.1.2 on 2022-10-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_city_user_phone_user_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_oauth',
            field=models.BooleanField(default=False),
        ),
    ]
