# Generated by Django 4.1.2 on 2022-10-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='John Doe', max_length=300),
        ),
    ]
