# Generated by Django 4.1.2 on 2022-10-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_credit_id_user_iban_id_user_id_card_user_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref_used_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
